# Generated by Django 4.0.4 on 2022-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='PatientsPrevConditions',
        ),
        migrations.AddField(
            model_name='patients',
            name='PatientsAllergies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patients',
            name='PatientsCardioVascular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patients',
            name='PatientsDiabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PatientsAddress',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PatientsBeenInfected',
            field=models.BooleanField(default=False),
        ),
    ]
