# Generated by Django 4.0.4 on 2022-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0002_remove_patients_patientsprevconditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('landline', models.IntegerField()),
                ('cell_phone', models.IntegerField()),
                ('been_infected', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_cardio_vascular', models.BooleanField(default=False)),
                ('has_allergies', models.BooleanField(default=False)),
                ('has_other_condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
