# Generated by Django 4.0.4 on 2022-06-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0003_citizeninfo_delete_patients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizeninfo',
            old_name='has_other_condition',
            new_name='conditions',
        ),
        migrations.RemoveField(
            model_name='citizeninfo',
            name='has_allergies',
        ),
        migrations.RemoveField(
            model_name='citizeninfo',
            name='has_cardio_vascular',
        ),
        migrations.RemoveField(
            model_name='citizeninfo',
            name='has_diabetes',
        ),
    ]
