# Generated by Django 4.0.4 on 2022-06-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0004_rename_has_other_condition_citizeninfo_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizeninfo',
            name='cell_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citizeninfo',
            name='landline',
            field=models.CharField(max_length=100),
        ),
    ]
