# Generated by Django 4.0.4 on 2022-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0005_alter_citizeninfo_cell_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizeninfo',
            name='conditions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
